bruteforce: bruteforce.c cipherImplementation.c timeProfiler.c
	gcc -O3 -march=native bruteforce.c cipherImplementation.c -o bruteforce
	gcc -O3 -march=native timeProfiler.c cipherImplementation.c -o timeProfiler